# Generated by Django 3.0.8 on 2020-07-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('cloudstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudstoreuser',
            name='base_folder',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='api.Folder'),
        ),
    ]
