# Generated by Django 3.0.8 on 2020-08-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200823_2216'),
        ('cloudstore', '0002_cloudstoreuser_base_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstoreuser',
            name='base_folder',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='api.Folder'),
        ),
    ]
