# Generated by Django 3.1 on 2020-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstore', '0003_auto_20200823_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstoreuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
