# Generated by Django 3.1 on 2020-08-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstore', '0004_auto_20200826_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('theme', models.CharField(default='dark', max_length=8)),
                ('view', models.CharField(default='tiles', max_length=8)),
                ('show_ext', models.BooleanField(default=False)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='settings',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
