# Generated by Django 3.1.1 on 2020-10-03 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstore', '0006_usersettings_view_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('allowed', models.BigIntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quota',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
