repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: /migrations/
        additional_dependencies: [
            django~=3.0,
            pylint-django~=2.2
        ]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        exclude: /migrations/
        additional_dependencies: [
            flake8-bugbear~=20.1,
            flake8-import-order~=0.18,
            flake8-tidy-imports~=4.1,
        ]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3