version: '3.8'

services:
    db:
        image: postgres:12.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env/.env.prod.db

    web:
        build:
            context: ./cloudstore
            dockerfile: ./Dockerfile.prod
        restart: unless-stopped
        command: gunicorn cloudstore.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
        expose:
            - 8000
        env_file:
            - ./.env/.env.prod
        depends_on:
            - db

    nginx:
        image: staticfloat/nginx-certbot
        restart: unless-stopped
        volumes:
            - ./nginx:/etc/nginx/user.conf.d:ro
            - static_volume:/home/app/web/static
            - letsencrypt:/etc/letsencrypt
        ports:
            - 80:80/tcp
            - 443:443/tcp
        env_file:
            - ./.env/.env.nginx
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
    letsencrypt: