version: '3.8'

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=cloudstore
            - POSTGRES_PASSWORD=cloudstore
            - POSTGRES_DB=cloudstore_dev

    web:
        build: ./cloudstore
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./cloudstore/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env/.env.dev
        depends_on:
            - db

volumes:
    postgres_data:
