[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py38']
exclude = '''
/(
    \.git
  | \env
  | migrations
)/
'''

[tool.pylint.master]
load-plugins = "pylint_django"
ignore= "migrations, __init__.py, env"

[tool.pylint.message_control]
disable = "C0114, C0115, C0116, C0330, C0326, C0415, R0801, R0903"

[tool.pylint.format]
max-line-length=100

[tool.pylint.design]
max-args=10
max-parents=20