# Generated by Django 3.1.1 on 2020-10-18 11:24

import cloudstore.apps.api.models.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'state',
                    models.IntegerField(
                        choices=[(0, 'Private'), (1, 'Public'), (2, 'Password Protected')],
                        default=0,
                    ),
                ),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='share',
            field=models.OneToOneField(
                default=cloudstore.apps.api.models.file._get_share,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.share',
            ),
        ),
    ]
