# Generated by Django 3.1.1 on 2020-10-19 10:43

import cloudstore.apps.api.models.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201018_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='share',
            field=models.OneToOneField(
                default=cloudstore.apps.api.models.file._get_share,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='file',
                to='api.share',
            ),
        ),
    ]
